#!/bin/bash

input_file=$1
output_file=$2

if [[ -f $input_file && -f $output_file ]]
then
	echo "Both files already exist!"
	exit 1
elif [[ ! -f $input_file ]]
then
	echo "Input file doesn't exist!"
	exit 1
else
	cat file | awk '!(NR%2){print$0;print r}NR%2{r=$0}' > $output_file
	
fi
