#!/bin/bash

echo "The script has started, please wait"
ping -c 3 $1 > /dev/null

if [[ $? -eq 0 ]]
then
	logger "`date '+%d-%m-%Y %H:%M:%S'` MyHostChecker: $1 is Up!"
	echo "Please see the logs"
else 
	logger "`date '+%d-%m-%Y %H:%M:%S'` MyHostChecker: $1 is Down!"
	echo "Please see the logs"
fi	
